var countryData ={
	cc: {
		name: 'Countries',
    area: 'Captain Marvel Photo',
		population: ' ',
		capital: ' ',
		president:' ',
		language: ' ',
    literacy rate: ' ',
  },		
  ru: {
		name: 'Russia',
    area: '17,098,242 sq km',
		population: '146.2 million',
		capital: 'Moscow',
		president:'Vladimir Putin',
		language: 'Russian',
    literacy: '99.73%',		
	},
	ca: {
    name: 'Canada',
    area: '9,984,670 sq km',
		population: '37.59 million',
		capital: 'Ottawa',
		president:'Justin Trudeau',
		language: 'French',
    literacy: '99%',
	},
	ch: {
    name: 'China',
    area: '9.6 million sq km',
		population: '1.398 billion',
		capital: 'Beijing',
		president:'Xi Jinping',
		language: 'Mandarin',
    literacy: '96.8 %',
	},
	us: {
		name: 'United State of America',
    area: '9.8 million sq km',
		population: '331 million',
		capital: 'Washington DC',
		president:'Joe Biden',
		language: 'English',
    literacy: '99%',
	},
	br: {
		name: 'Brazil',
		area: '8,515,767 sq km',
		population: '211 million',
		capital: 'Brasília',
		president:'Jair Bolsonaro',
		language: 'Portuguese',
    literacy: '93.23%',
		
	},
	au: {
		name: 'Australia',
		area: '7,617,930 sq km',
		population: '25.36 million',
		capital: 'Canberra',
		president:'Scott Morrison',
		language: 'English (80%)',
    literacy: '95.34%',		
	},
};